### ISSUE TITLE
Suggest you make the plot grey scale

### ISSUE THREAD

**Issue by K-C-Martin** [MatthewvanEyssen/EucXylo-workshop#2]
https://github.com/MatthewvanEyssen/EucXylo-workshop/blob/ba28b18841f4db3b2524a6ab6d55f15538bdb3aa/output_species_count/spiecies_counts.R#L77

Not all journals accept colour plots (or it may cost more!)

**Comment by MatthewvanEyssen** [comment]
Are you sure !!!!!!!!!!!!!!!!!!!!!!!!! I do not think so??
